[package]
name = "graph_experimentation"
version = "0.1.0"
edition = "2024"

[dependencies]
neo4rs = "0.8.0"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
